#!/usr/bin/env bash

set -e

if [ -d node_modules ]; then
    export PATH=$PWD/node_modules/bin:$PATH
fi

npm install
npm install bower
bower install

if [ ! -f src/lib/depends_parse.js -o src/lib/depends_parse.js -ot src/lib/depends_parse.pegjs ] ; then
	node_modules/.bin/pegjs src/lib/depends_parse.pegjs
	sed -i~ -e '1s/.*/define(function() {/' -e '$s/()//' src/lib/depends_parse.js || rm -f src/lib/depends_parse.js
fi
