name: test
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - *
jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - run: npm install yarn
    - run: make check
